DROP TABLE IF EXISTS dms;
CREATE DATABASE dms;
USE dms;

CREATE TABLE person(
	pid INT PRIMARY KEY AUTO_INCREMENT,
	pname VARCHAR(50) NOT NULL UNIQUE,
	ppass VARCHAR(50) NOT NULL
);

CREATE TABLE t_group(
	gid INT PRIMARY KEY AUTO_INCREMENT,
	gname VARCHAR(50) UNIQUE NOT NULL,
	shareId VARCHAR(32) UNIQUE NOT NULL
);

CREATE TABLE group_person(
	gpid VARCHAR(255) PRIMARY KEY,
	pid INT NOT NULL,
	gid INT NOT NULL,
	person_permitted BOOLEAN NOT NULL DEFAULT FALSE,
	CONSTRAINT fk_person_gp FOREIGN KEY(pid) REFERENCES person(pid),
	CONSTRAINT fk_group_gp FOREIGN KEY(gid) REFERENCES `group`(gid)
);

CREATE TABLE document(
	did CHAR(32) PRIMARY KEY,
	ddata LONGBLOB NOT NULL,
	dname VARCHAR(255) NOT NULL,
	gid INT NOT NULL,
	updatedate DATETIME,
	dpass VARCHAR(255),
	CONSTRAINT fk_group_document FOREIGN KEY(gid) REFERENCES `group`(gid)
);

